name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Contents and pull-requests are for release-please to make releases.
      issues: write # Needed to create labels
      pull-requests: write
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release

  release-sdk:
    needs: ['release-please']
    permissions:
      id-token: write
      contents: write
      attestations: write
    if: ${{ needs.release-please.outputs.release-created == 'true' }}
    uses: ./.github/workflows/publish.yml
    with:
      dry_run: false
